# Generated by Django 4.2 on 2025-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='aggravation_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='non_response_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='response_100_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='response_50_74_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='response_75_99_2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
